name: Automated Release

on:
  push:
    tags:
      - "v[0-9]+"

jobs:
  release:
    name: Release Addon
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${secrets.CURSEFORGE_API_TOKEN}
